version: '3.4'
services:
  wellness-roots-frontend:
    image: node:alpine
    container_name: wellness-roots-frontend
    entrypoint: /bin/sh
    ports:
      - 3000:3000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    env_file:
      - .env
    tty: true
